from .base import BaseLLM, GenerationResult, LLMCapabilities
from .generation import (
    _clear_device_cache,
    _resolve_model_inputs,
    _should_fallback_to_sequential,
    _strict_mc_generated_answer_complete,
    _token_id_list_from_encoded,
    encode_chat,
    generate_many,
    generate_one,
    to_hf_chat,
)
from .huggingface import HuggingFaceLLM
from .loading import load_model_and_tokenizer
from .openai_backend import OpenAILLM
from .registry import (
    get_registered_llm_factory,
    get_registered_llm_capabilities,
    load_llm,
    register_llm,
    registered_llm_names,
    resolve_llm_backend,
    resolve_llm_capabilities,
    unregister_llm,
)
from .scoring import audit_choice_tokenization, score_choices, score_logprob_answer, score_p_true
from .sampling import (
    build_sampling_spec,
    enumerate_expected_sample_keys,
    load_sampling_cache_candidate,
    normalize_sample_records,
    sample_record_key,
    sample_record_key_values,
    sample_records_for_groups,
    sampling_spec_hash,
    sort_sample_records,
)

__all__ = [
    "BaseLLM",
    "GenerationResult",
    "LLMCapabilities",
    "_clear_device_cache",
    "_resolve_model_inputs",
    "_should_fallback_to_sequential",
    "_strict_mc_generated_answer_complete",
    "_token_id_list_from_encoded",
    "build_sampling_spec",
    "encode_chat",
    "enumerate_expected_sample_keys",
    "generate_many",
    "generate_one",
    "audit_choice_tokenization",
    "get_registered_llm_factory",
    "get_registered_llm_capabilities",
    "HuggingFaceLLM",
    "load_llm",
    "load_model_and_tokenizer",
    "load_sampling_cache_candidate",
    "normalize_sample_records",
    "OpenAILLM",
    "register_llm",
    "registered_llm_names",
    "resolve_llm_backend",
    "resolve_llm_capabilities",
    "sample_record_key",
    "sample_record_key_values",
    "sample_records_for_groups",
    "sampling_spec_hash",
    "score_logprob_answer",
    "score_choices",
    "score_p_true",
    "sort_sample_records",
    "to_hf_chat",
    "unregister_llm",
]
